/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoinFlip } from "./CoinFlip";

export { CoinFlip__factory } from "./factories/CoinFlip__factory";
